version: '3.8'

services:
  discord-media-request-bot:
    container_name: media-request-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
